In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,3],[10,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [10,  8]])>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10,9],[8,7],[6,5]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 8,  7],
       [ 6,  5]])>

In [10]:
another_matrix.ndim

2

In [13]:
tensor = tf.constant([[[1,2],[3,4],[21,21]],[[5,6],[7,8],[23,43]]])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [21, 21]],

       [[ 5,  6],
        [ 7,  8],
        [23, 43]]])>

In [14]:
tensor.ndim

3

In [16]:
#tf.Variable
change_tensor = tf.Variable([10,7])
unchange_tensor = tf.constant([10,7])
change_tensor, unchange_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [17]:
change_tensor[0].assign(7)
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [19]:
# cant do: unchange_tensor[0].assign(1000)

In [21]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(41)
random_2 = random_2.uniform(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.33765244, 0.4655341 ],
       [0.30376935, 0.43766797],
       [0.7493447 , 0.73561966]], dtype=float32)>

In [38]:
not_shuffled = tf.constant([[10,7],[2,3],[4,5]])
print(not_shuffled.ndim)

tf.random.set_seed(41) #makes below random shuffle given the same results
s = tf.random.shuffle(not_shuffled, seed=42) #not global seed but operation seed
s

2


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  5],
       [ 2,  3],
       [10,  7]])>

In [39]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [41]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [45]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [47]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [48]:
A.ndim

3

In [49]:
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [50]:
A.dtype

tf.int32