In [1]:
import tensorflow as tf
import numpy as np

In [16]:
t = tf.zeros(shape=(2,3,2,3))
t

<tf.Tensor: shape=(2, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [17]:
t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [18]:
t[1][1][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [19]:
t[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 2, 1), dtype=float32, numpy=
array([[[[0.],
         [0.]]]], dtype=float32)>

In [20]:
# create a rank 2 tensor

t2 = t[...,tf.newaxis]
t2

<tf.Tensor: shape=(2, 3, 2, 3, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]]],



       [[[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]]]], dtype=float32)>

In [21]:
tf.expand_dims(t, axis=1)

<tf.Tensor: shape=(2, 1, 3, 2, 3), dtype=float32, numpy=
array([[[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]]], dtype=float32)>