In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [3]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [4]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [5]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [6]:
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [7]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]])>

In [8]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [10]:
tensor.shape

TensorShape([2, 2])

In [13]:
X = tf.constant([[1,2],[3,4],[5,6]])
print(tensor.shape, X.shape)
tf.matmul(X,tensor)

(2, 2) (3, 2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[16, 15],
       [42, 37],
       [68, 59]])>

In [16]:
Y = tf.reshape(X, shape=(2,3))
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [18]:
print(tensor.shape, Y.shape)
tf.matmul(tensor, Y)

(2, 2) (2, 3)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[38, 55, 72],
       [19, 26, 33]])>

In [22]:
X, tf.transpose(X), Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [23]:
A = tf.constant([[1.1,1.2]])
A

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1.1, 1.2]], dtype=float32)>

In [24]:
B = tf.cast(A, dtype=tf.float16)
B

<tf.Tensor: shape=(1, 2), dtype=float16, numpy=array([[1.1, 1.2]], dtype=float16)>