In [1]:
import tensorflow as tf
import numpy as np


In [2]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [3]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [16]:
E = tf.random.uniform(minval=1,maxval=100, shape=(50,), dtype=tf.int32)
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([24, 91, 49, 37, 77, 11, 75, 77,  3, 67, 13, 34, 25, 37, 22, 21, 49,
       77, 47, 47, 97,  2, 24, 20, 33, 95, 55, 40, 54, 94, 10, 33, 48, 95,
        3, 65, 15, 81, 66, 77, 30, 87, 23, 50, 81, 33, 51,  8, 42, 81])>

In [18]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [20]:
tf.reduce_min(E), tf.reduce_max(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=97>)

In [ ]:
tf.reduce_mean(E), tf.reduce_sum(E)

AttributeError: module 'tensorflow' has no attribute 'reduce_std'

In [24]:
import tensorflow.math as tfm

In [29]:
F = tf.cast(E, dtype=tf.float16)
print(tfm.reduce_std(F))
print(tfm.reduce_variance(F))

tf.Tensor(28.16, shape=(), dtype=float16)
tf.Tensor(793.0, shape=(), dtype=float16)


In [33]:
T = tf.random.uniform(shape=(50,))
T

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.39445388, 0.34720576, 0.5855731 , 0.53474474, 0.66461825,
       0.7860304 , 0.50751615, 0.34618235, 0.6234963 , 0.60007584,
       0.57961404, 0.4418726 , 0.76675916, 0.04946852, 0.33756638,
       0.24972022, 0.9523412 , 0.5588535 , 0.6556783 , 0.5953078 ,
       0.41728377, 0.9051769 , 0.11893487, 0.51162016, 0.7243432 ,
       0.58774364, 0.65013564, 0.02139282, 0.4515134 , 0.93678033,
       0.750208  , 0.536664  , 0.49462044, 0.54543257, 0.5373219 ,
       0.08779955, 0.08407152, 0.5665678 , 0.08243775, 0.05743682,
       0.21549535, 0.47094023, 0.39016628, 0.7990161 , 0.67207503,
       0.17760527, 0.9395387 , 0.06606305, 0.48892212, 0.95825243],
      dtype=float32)>

In [35]:
maxarg = tf.argmax(T)
maxarg

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [36]:
T[maxarg]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9582524299621582>

In [37]:
T = tf.random.uniform(shape=(1,1,1,1,1,1,1,50))
T

<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[[[0.7220572 , 0.00237656, 0.5817461 , 0.751127  ,
              0.1887815 , 0.47284234, 0.830673  , 0.64926565,
              0.77432203, 0.55785537, 0.63808966, 0.18248618,
              0.7759588 , 0.38043547, 0.56337035, 0.23124957,
              0.6112344 , 0.5396904 , 0.99303174, 0.5368563 ,
              0.3361324 , 0.19769335, 0.7426684 , 0.0513643 ,
              0.29809177, 0.47838068, 0.2531755 , 0.3751533 ,
              0.39183843, 0.20878577, 0.34096265, 0.18895125,
              0.63220406, 0.2749598 , 0.6951281 , 0.6170443 ,
              0.13010955, 0.04733598, 0.3024807 , 0.33782935,
              0.9893203 , 0.13015342, 0.52003145, 0.0784502 ,
              0.08524942, 0.47915113, 0.24657726, 0.6371572 ,
              0.83935106, 0.43295765]]]]]]]], dtype=float32)>

In [38]:
tf.squeeze(T)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7220572 , 0.00237656, 0.5817461 , 0.751127  , 0.1887815 ,
       0.47284234, 0.830673  , 0.64926565, 0.77432203, 0.55785537,
       0.63808966, 0.18248618, 0.7759588 , 0.38043547, 0.56337035,
       0.23124957, 0.6112344 , 0.5396904 , 0.99303174, 0.5368563 ,
       0.3361324 , 0.19769335, 0.7426684 , 0.0513643 , 0.29809177,
       0.47838068, 0.2531755 , 0.3751533 , 0.39183843, 0.20878577,
       0.34096265, 0.18895125, 0.63220406, 0.2749598 , 0.6951281 ,
       0.6170443 , 0.13010955, 0.04733598, 0.3024807 , 0.33782935,
       0.9893203 , 0.13015342, 0.52003145, 0.0784502 , 0.08524942,
       0.47915113, 0.24657726, 0.6371572 , 0.83935106, 0.43295765],
      dtype=float32)>

In [40]:
## ONE HOT ENCODING

some_list = [0,1,2,3,4,5]

tf.one_hot(some_list, depth=6)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>